// This file is auto-generated by `ohara build:site`
// Manual edits will be overwritten

import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  integrations: [
    starlight({
      title: 'Ohara Docs',
      customCss: ['./src/custom.css'],
      social: {},
      sidebar: [],
    }),
  ],
});
